### ISSUE TITLE
Asking for 6 updates in the code.

### ISSUE THREAD

**Issue by wyf180** [nks770/WinUpdate_XP_x86#1]
I used the program in my xp vm and found lack some updates,but when I googled them I found 6 updates could only find dead links including kb895961 kb954920 kb955417 kb960680 kb2264107 kb971314.so could you share the copy of these updates for me?

**Comment by nks770** [comment]
Hi there!  Thank you so much for your interest in my project.  As the years go by, links for these XP hotfixes are going dead, and it has taken me a lot of searching to recover many of them.  I maintain an offline archive with every hotfix file referenced in the source code, and am happy to provide any that anyone needs.  I do have an eventual plan to find a way to publicly host my whole archive, but until then, I zipped up the 6 specific ones you asked for and uploaded to mega:

[https://mega.nz/file/eYJSEJzY#0M-kNff7jdzfXbRk7i2Q6MFRdLJi9m3uVa9YabUOnXg](https://mega.nz/file/eYJSEJzY#0M-kNff7jdzfXbRk7i2Q6MFRdLJi9m3uVa9YabUOnXg)

I am aware of some bugs in the code which I am continuing to work on in my free time, but I'm happy to respond to any that cause immediate grief.  Thanks again for getting in touch.
